OPTIONS (SKIP=1)
LOAD DATA
INFILE 'CHANNELS.csv'
REPLACE
INTO TABLE bdii_1010832.CHANNELS
FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(CHANNEL_ID CHAR(1),
CHANNEL_DESC CHAR(255),
CHANNEL_CLASS CHAR(255),
COST_SALE_PCT decimal EXTERNAL)