OPTIONS (SKIP=1)
LOAD DATA
INFILE 'employees.csv'
REPLACE
INTO TABLE bdii_1010832.employees
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(COMMISSION_PCT decimal EXTERNAL,
EMAIL CHAR(50),
EMPLOYEE_ID integer external,
FIRST_NAME INTEGER EXTERNAL,
HIRE_DATE DATE "dd-MON-rr",
JOB_ID CHAR(40),
LAST_NAME CHAR(50),
MANAGER_ID integer external,
PHONE_NUMBER CHAR(100),
SALARY integer external
)